# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  subscription: 'Visual Studio Enterprise – MPN (734fc759-c3a2-4e22-a478-301dc5b10496)'
  containerRegistry: '{"loginServer":"horondistaging.azurecr.io", "id" : "/subscriptions/734fc759-c3a2-4e22-a478-301dc5b10496/resourceGroups/Horondi/providers/Microsoft.ContainerRegistry/registries/HorondiStaging"}'
  

  # Agent VM image name
  vmImageName: 'ubuntu-16.04'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build    
    steps:
     - task: DownloadSecureFile@1
       inputs:
        secureFile: '.env'
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: 'ls'

     - task: Docker@0
       displayName: 'Build an image'
       inputs:
          azureSubscription: $(subscription)
          azureContainerRegistry: $(containerRegistry)
          action: 'Build an image'
     - task: Docker@0
       displayName: 'Push an image'
       inputs:
         azureSubscription: $(subscription)
         azureContainerRegistry: $(containerRegistry)
         action: 'Push an image'