name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ gh-actions-ci ]
  pull_request:
    branches: [ gh-actions-ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Docker Compose Action
        # You may pin to the exact commit or the version.
        # uses: isbang/compose-action@8df5a465825a807c86520a4d86207471b512d249
        uses: isbang/compose-action@v0.1.1
        with:
          # relative path to compose file
          compose-file: ./docker/docker-compose.yml
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - run: npm install
      - run: npm run test

      - name: fix code coverage paths
        run: | 
          sed -i 's/\/home\/runner\/work\/horondi_client_be\/horondi_client_be\//\/github\/workspace\//g' test-report.xml
          sed -i 's/\/home\/runner\/work\/horondi_client_be\/horondi_client_be\//\/github\/workspace\//g' coverage/lcov.info
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          CI: true

